### ISSUE TITLE
onChange function doesn´t change useState variable

### ISSUE THREAD

**Issue by mvrochar** [mkhstar/suneditor-react#102]
I´m trying to set a variable state with the content of the SunEditor, but the variable doesn´t change its state.

My Code:

```
const [values, setValues] = useState({value: ''});

function handleChange(content) {
    setValues({
      values: content
    })
    console.log(`SET VALUES ${JSON.stringify(values)}`)
    console.log(`TYPEOF ${typeof(content)}`)
  }

  return (
    <div className={classes.textEditor}>
      <SunEditor
        height="500"
        setContents={ServiceContractLayout(contract[0], false)}
        setOptions={{
          height: 200,
          plugins: [sendButton],
          buttonList: [
            ['font', 'fontSize'],
            ['bold', 'underline', 'italic', 'strike'],
            ['removeFormat', 'fontColor'],
            ['align', 'indent', 'list'],
            ['undo', 'redo'],
            ['save', 'preview', 'print'],
            ['send'],
          ], // Or Array of button list, eg. [['font', 'align'], ['image']]
          callBackSave: values => callBackFunction(values),
        }}
        onChange={handleChange}
      />
    </div>
  );
```

Also, I would like to know if there is another way to get the value of the editor and pass it to a function.

Thanks in advance!

Value still the same:

![image](https://user-images.githubusercontent.com/49122424/91356680-7161d800-e7c6-11ea-80a4-da4e5caa3488.png)

**Comment by mkhstar** [comment]
@mvrochar 
You have got a typo
In the setValues function you are setting the property **values** not **value**
It should be 
```javascript
 setValues({
      value: content
 })
```

**Comment by mkhstar** [comment]
You wouldn't see any effect but this is just normal because at the time the handleChange closure is captured the values variable was {value: ''} so anytime you call the handleChange it will log the same variable.  **The handleChange's job is not to keep in sync with the state, it is just to give you the changes to the editor.**
You can use your developer tools to confirm that your state variables is actually changing or you can press a button to log the state's variable

**Comment by mvrochar** [comment]
OK, thank you very much!
