### ISSUE TITLE
Using multiple SunEditor on the same page

### ISSUE THREAD

**Issue by rajmera** [mkhstar/suneditor-react#125]
I have a tabbed page with two tabs.

I added the SunEditor to be displayed on both the tabs. However, when I toggle the tabs the contents of one tab get over-written by the contents of the second tab. 

Also, the onChange is called when the tabs are loaded, even though the content didn't change. I would think the onChange will only be called if the contents change. Am I missing something?

`      <div className="cw-form-group">
         <label className="cw-label">
            {__("Message", "content-workflow")}
         </label>
         <SunEditor
            autoFocus={true}
            placeholder={__("Add email content...", "content-workflow")}
            setContents={props.content}
            onChange={(content) => props.onChange(content, props.notification)}
         />
         <div className="cw-big-divider"></div>
      </div>`

**Comment by mkhstar** [comment]
Hi @rajmera 
For the content of the editors been overridden might depend on what is actually coming from `props.content`. 
Also yes when you switch to the other tab the `onChange` event fires because the `setContents` prop was set and that is because when you switch to the new tab it re-renders the suneditor all over again.
