### ISSUE TITLE
If I upload an image 1st, then I cannot use any text (only in code/HTML mode)

### ISSUE THREAD

**Issue by Octopusboom** [mkhstar/suneditor-react#168]
O open the editor and upload an image. After that I cannot type in the editor anything.

Am I doing something wrong?

Thank you!

**Comment by Octopusboom** [comment]
The same issue is on the official Demo too.

**Comment by mkhstar** [comment]
Hi @Octopusboom 
I understand the problem that you are facing. It is somehow difficult to figure what to do next after uploading image to the editor. When you follow the image I have attached, after uploading the image, you have to click that button to activate the editor back. @JiHong88  I think we could make it so that when the using clicks after the image it activates the editor for text input again

**Comment by Octopusboom** [comment]
Thank you for your answer and for the great work!
An idea would be after the upload event to change the focus on the textarea. Just saying :)

**Comment by JiHong88** [comment]
@Octopusboom  @mkhstar 
`mediaAutoSelect` option has been added since v2.36.0.
```javascript
{
  mediaAutoSelect: false
}
```

**Comment by mkhstar** [comment]
Thanks
