### ISSUE TITLE
Error when using buttonList after upgrade to v3.0.0

### ISSUE THREAD

**Issue by esp-quyen** [mkhstar/suneditor-react#207]
I meet this error when upgrading to version 3.0.0
![image](https://user-images.githubusercontent.com/78066823/118420190-6ea66a80-b6e8-11eb-9508-fedea357360b.png)
This is my code:
```
<SunEditor
	width="100%"
	setContents={bodyText}
	onChange={(content) => {
		setBodyText(content);
		onSetBodyText && onSetBodyText(content);
	}}
	onImageUploadBefore={onImageUploadBefore}
	setOptions={{
		lang: "en",
		buttonList: buttonList.basic,
	}}
/>
```
Suneditor version
```
"suneditor": "^2.39.0",
"suneditor-react": "^3.0.0",
```
React version: 17.0.1

**Comment by mkhstar** [comment]
hi @esp-quyen 
This error is occurring because you are setting the lang property in setOptions to a **`string`** value. 
If you set the lang property in `setOptions` suneditor-react passes all the responsibility of setting the language to you. To see how to set the lang property using `setOptions` see the core suneditor documentation

To make suneditor-react help you in setting the lang property use the prop `lang` instead. Example below
```jsx
<SunEditor
	width="100%"
	setContents={bodyText}
        lang="en"
	onChange={(content) => {
		setBodyText(content);
		onSetBodyText && onSetBodyText(content);
	}}
	onImageUploadBefore={onImageUploadBefore}
	setOptions={{
		buttonList: buttonList.basic,
	}}
/>
```

When set this way suneditor-react will pass the proper defintions to the setOptions property for you behind the scenes. Notice that I have removed the `lang` property in `setOptions`. 
Also you might be interested to know that the default value of lang is en so you don't need to set it at all in your case
