### ISSUE TITLE
onSave event not exist.

### ISSUE THREAD

**Issue by eritondev-stack** [mkhstar/suneditor-react#238]
editor.onSave = function (contents, core) {console.log(contents) } not exist in the list fuctions.

**Comment by mkhstar** [comment]
@eritondev-stack 
The onSave function doesn't exist yet on the core suneditor package, If you need this functionality use the `callBackSave` method in `setOptions`

**Comment by cglacet** [comment]
@mkhstar  `callBackSave` seems to be clunky, it doesn't get updated when the input function changes.

Is there a proper way to pass a save function? I can't find anything about this in the documentation. That's a bit confusing because I guess nobody can use that library without the ability to save.

**Comment by cglacet** [comment]
Ok, I found a way, you can retrieve the content using `editor.current?.getContents(true)`, which mean we can have our own save button (you need to remove `callBackSave: props.onSave`, otherwise you might have bad surprises).  

The code more or less look like this: 

```tsx
import SunEditorCore from "suneditor/src/lib/core";
const SunEditor = dynamic(() => import("suneditor-react"), {
  ssr: false,
});

type EditorProps = {onSave?: (content: string | undefined) => void};

function Editor(props: EditorProps){
  const editor = useRef<SunEditorCore>();
  const getSunEditorInstance = (sunEditor: SunEditorCore) => {
    editor.current = sunEditor;
  };
  return <>
    <SunEditor getSunEditorInstance={getSunEditorInstance}  />
    <Button onClick={() => props.onSave?.(editor.current?.getContents(true))}>
        Sauvegarder
     </Button>
  </>
}
```

That's a bit uggly, but I didn't want to search for a real solution. In the mean time, this works at least.

Note: `getContents(true)` doesn't seem to appear in the online doc, but it's documented in the library: 


> SunEditor.getContents(onlyContents: boolean): string
> @description — Gets the contents of the suneditor
>
> @param onlyContents — Return only the contents of the body without headers when the "fullPage" option is true
