### ISSUE TITLE
Next.JS - this._iframeAutoHeight is not a function

### ISSUE THREAD

**Issue by estelleal** [mkhstar/suneditor-react#239]
Hello,

I'm trying to use suneditor with NextJS, the editor is well displayed but when i'm writing inside, the editor looks to reload and i got this error : 

```
Unhandled Runtime Error
TypeError: this._iframeAutoHeight is not a function

Call Stack
Object._resourcesStateChange
node_modules/suneditor/src/lib/core.js (5251:0)
```

Maybe someone already got this problem ?

Thanks

**Comment by qtarant** [comment]
Hello.
I have the exact same problem.
I have a working suneditor working on a create-react-app application but on NextJS it is not working because this error.

**Comment by MakiMarc** [comment]
It would be helpful if you could provide a code example of how you implemented the SunEditor in your component.

But I suspect you are using `setContents` to set the content. Use `defaultValue` instead and the error should not appear anymore.

Two-way binding should not be used. This is because the setContents statement triggers the onChange event. If you want to set the initial value of the editor, use the `defaultValue` prop.

**Comment by mkhstar** [comment]
@estelleal please provide a code example. But I think @MakiMarc 's comment will help you fix the issue

**Comment by krAlena** [comment]
Hi! I have had the same issue. 

This solution is works for me: 
1) Dynamic import
```
const SunEditor = dynamic(() => import("suneditor-react"), {
    ssr: false,
});
```

2) Use the editor without property "plugins"
