### ISSUE TITLE
setContents not working with react 18 on page load

### ISSUE THREAD

**Issue by anilkonsal** [mkhstar/suneditor-react#296]
I am using react v18 with suneditor-react. Not seeing the content loaded in the editor.

Seeing this error in console:
```
Uncaught TypeError: core._resourcesStateChange is not a function
    at core.js:6190:1
```
![Screen Shot 2022-12-08 at 11 08 48 am](https://user-images.githubusercontent.com/2535407/206324518-390aeaa4-5afb-4bd0-809f-8ca7bb31dd96.jpg)

**Comment by VHarastei** [comment]
I have the same problem. Is there some kind of solution?

**Comment by lgehrke6** [comment]
Any news on this problem? currently also running into this problem using react 18.2.0

**Comment by mkhstar** [comment]
Apparently, react 18 calls useEffects twice when `StrictMode` is used, which destroys the suneditor and creates it again. Due to this the previous suneditor's core will not exist which triggers the error. 
@JiHong88 I couldn't find the line in the latest version https://github.com/JiHong88/suneditor/blob/ea4a46fd3c5ae18c0194e8085953f695a83eba34/src/lib/core.js#L5943-L5949
I wonder how it ended up in the dist

**Comment by mkhstar** [comment]
Even though on production it will work correctly but if you want a way around it, don't use `StrictMode` until this bug is fixed

**Comment by mkhstar** [comment]
This should be fixed in the latest version
