### ISSUE TITLE
How to get the text/content of a selection

### ISSUE THREAD

**Issue by Mikco11** [mkhstar/suneditor-react#60]
Hello,
i am trying to implement "comment" functionality i should say.
When I highlight some text in editor with my mouse, then i want to click on the button which will add my custom component with text I highlighted in editor. Is it possible ? I couldnt find any editor method in documentation.

**Comment by mkhstar** [comment]
Hi @Mikco11 
That must be a good idea. I don't think this feature is implemented in the core suneditor package. @JiHong88 what do you think about a onSelectChange event handler

**Comment by Mikco11** [comment]
I am not sure if onChange type would be the best at least in my case. I dont want to trigger it on every select that user will do. Just when he clicks on the button it will get the select text/content.

**Comment by mkhstar** [comment]
Hi @Mikco11,
There is no way that you can handle whatever you select without us providing an event handler. When we provide an event handler, you could listen with your own method and set the state of the selection, so that when a user clicks a button you can get the selection content from the state.

**Comment by JiHong88** [comment]
@Mikco11 @mkhstar "onSelectionChange" event is not supported at the FireFox.
It could be implemented indirectly, but it would not be accurate.
